Header branch
susird/crassus-js pull request #3
Opened 2020-10-01 22:39 UTC by susird

Creating header of Crassus and mobile version

![image](https://user-images.githubusercontent.com/42523734/94867432-e0a29b80-0406-11eb-9a54-d18571fe1b22.png)
![image](https://user-images.githubusercontent.com/42523734/94867545-0f207680-0407-11eb-8ba1-afcecf8d4b88.png)

2020-10-03 05:08 UTC, anyruizd requested changes
A lot of comments, but most of them are to remove repeated code 😄 Well done!

2020-10-03 05:08 UTC, anyruizd commented on Components/Header.js
> +   function toggleHamburger() {
I'm not sure this function should have that indentation, could you please check it?

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    display: flex;
```suggestion
```
This code is not needed here since it already exists in the default state, i.e. in the line 33, i.e. when there's no media query.

2020-10-03 05:08 UTC, anyruizd commented on index.css
>    text-align: center;
This property seems is not necessary, and neither`font-weight: bold` in line 17. Please review.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +  position: relative;
This doesn't make any difference if is not in the code, are you sure it's needed?

2020-10-03 05:08 UTC, anyruizd commented on index.css
>    -webkit-background-clip: text;
This should be next to `background-clip: text` in line 14 since they're the same property with a prefix.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    margin-left: 10px;
It's preferable to play with paddings in the container instead of doing first margins. Let the margins be your last choice, and try to do this with a `padding-left: 10px` in the container.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    font-weight: bold;
This property seems not to be needed. Please review if it is.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    width: 254px;
Please review this properties because there are a lot of them that are duplicated in lines 87-93

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +  flex-direction: row;
AFAIK this is not needed since the row is the direction by default.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    flex-direction: column;
This property is not needed here, since when it's a mobile device the display is block and a property like this one only works under `display: flex;`
```suggestion
```

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +  justify-content: center;
This property seems to not be needed, since it makes no difference if it's in the code or not. Please review if it's needed.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +    justify-content: normal;
If you remove the `justify-content: center` in line 79 this property won't be needed here anymore.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +.nav-links {
Please move the block of code corresponding to `.nav-links` from line 76 to line 81 to be before its variations (`.nav-links::after`, `.nav-links a`, `.nav-links:hover a`). It should be put in line 50.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +  border: 0;
These properties are no needed. Please remove.

2020-10-03 05:08 UTC, anyruizd commented on index.css
> +  flex-direction: row;
These properties are no needed. It makes no difference to have them in the code or not.

2020-10-04 04:11 UTC, susird commented on index.css
>    -webkit-background-clip: text;
How should it go? line 21 is not necessary

2020-10-04 04:13 UTC, susird commented on index.css
> +  justify-content: center;
Yes, the property it's neede to align the after in right position

2020-10-04 07:43 UTC, anyruizd commented on index.css
>    -webkit-background-clip: text;
Heh, sorry, Im' talking about line `-webkit-background-clip: text;` that should go next to `background-clip: text`.

2020-10-05 00:44 UTC, merged